[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "lingua-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepl>=1.32.0",
]

[project.scripts]
t = "lingua_cli.cli:main"

[tool.setuptools]
package-dir = {"" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
